/*
 * This file is generated by jOOQ.
 */
package me.aa07.parautil.database.tables.records;


import javax.annotation.Generated;

import me.aa07.parautil.database.tables.LinkedAccounts;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LinkedAccountsRecord extends UpdatableRecordImpl<LinkedAccountsRecord> implements Record2<String, Long> {

    private static final long serialVersionUID = -12864656;

    /**
     * Setter for <code>paradise_mc.linked_accounts.uuid</code>.
     */
    public void setUuid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>paradise_mc.linked_accounts.uuid</code>.
     */
    public String getUuid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>paradise_mc.linked_accounts.fuid</code>.
     */
    public void setFuid(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>paradise_mc.linked_accounts.fuid</code>.
     */
    public Long getFuid() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return LinkedAccounts.LINKED_ACCOUNTS.UUID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return LinkedAccounts.LINKED_ACCOUNTS.FUID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getFuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getFuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LinkedAccountsRecord value1(String value) {
        setUuid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LinkedAccountsRecord value2(Long value) {
        setFuid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LinkedAccountsRecord values(String value1, Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LinkedAccountsRecord
     */
    public LinkedAccountsRecord() {
        super(LinkedAccounts.LINKED_ACCOUNTS);
    }

    /**
     * Create a detached, initialised LinkedAccountsRecord
     */
    public LinkedAccountsRecord(String uuid, Long fuid) {
        super(LinkedAccounts.LINKED_ACCOUNTS);

        set(0, uuid);
        set(1, fuid);
    }
}
