/*
 * This file is generated by jOOQ.
 */
package me.aa07.parautil.database.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import me.aa07.parautil.database.tables.Players;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlayersRecord extends UpdatableRecordImpl<PlayersRecord> implements Record5<String, String, String, Timestamp, Timestamp> {

    private static final long serialVersionUID = 273180203;

    /**
     * Setter for <code>paradise_mc.players.uuid</code>.
     */
    public void setUuid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>paradise_mc.players.uuid</code>.
     */
    public String getUuid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>paradise_mc.players.last_username</code>.
     */
    public void setLastUsername(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>paradise_mc.players.last_username</code>.
     */
    public String getLastUsername() {
        return (String) get(1);
    }

    /**
     * Setter for <code>paradise_mc.players.last_ckey</code>.
     */
    public void setLastCkey(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>paradise_mc.players.last_ckey</code>.
     */
    public String getLastCkey() {
        return (String) get(2);
    }

    /**
     * Setter for <code>paradise_mc.players.first_seen</code>.
     */
    public void setFirstSeen(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>paradise_mc.players.first_seen</code>.
     */
    public Timestamp getFirstSeen() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>paradise_mc.players.last_seen</code>.
     */
    public void setLastSeen(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>paradise_mc.players.last_seen</code>.
     */
    public Timestamp getLastSeen() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, String, String, Timestamp, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, String, String, Timestamp, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Players.PLAYERS.UUID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Players.PLAYERS.LAST_USERNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Players.PLAYERS.LAST_CKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return Players.PLAYERS.FIRST_SEEN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return Players.PLAYERS.LAST_SEEN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getLastUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getLastCkey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getFirstSeen();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getLastSeen();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getLastUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getLastCkey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getFirstSeen();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getLastSeen();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PlayersRecord value1(String value) {
        setUuid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PlayersRecord value2(String value) {
        setLastUsername(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PlayersRecord value3(String value) {
        setLastCkey(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PlayersRecord value4(Timestamp value) {
        setFirstSeen(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PlayersRecord value5(Timestamp value) {
        setLastSeen(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PlayersRecord values(String value1, String value2, String value3, Timestamp value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PlayersRecord
     */
    public PlayersRecord() {
        super(Players.PLAYERS);
    }

    /**
     * Create a detached, initialised PlayersRecord
     */
    public PlayersRecord(String uuid, String lastUsername, String lastCkey, Timestamp firstSeen, Timestamp lastSeen) {
        super(Players.PLAYERS);

        set(0, uuid);
        set(1, lastUsername);
        set(2, lastCkey);
        set(3, firstSeen);
        set(4, lastSeen);
    }
}
