/*
 * This file is generated by jOOQ.
 */
package me.aa07.parautil.database;


import javax.annotation.Generated;

import me.aa07.parautil.database.tables.LinkTokens;
import me.aa07.parautil.database.tables.LinkedAccounts;
import me.aa07.parautil.database.tables.Players;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>paradise_mc</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index LINKED_ACCOUNTS_PRIMARY = Indexes0.LINKED_ACCOUNTS_PRIMARY;
    public static final Index LINK_TOKENS_PRIMARY = Indexes0.LINK_TOKENS_PRIMARY;
    public static final Index PLAYERS_PRIMARY = Indexes0.PLAYERS_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index LINKED_ACCOUNTS_PRIMARY = Internal.createIndex("PRIMARY", LinkedAccounts.LINKED_ACCOUNTS, new OrderField[] { LinkedAccounts.LINKED_ACCOUNTS.UUID }, true);
        public static Index LINK_TOKENS_PRIMARY = Internal.createIndex("PRIMARY", LinkTokens.LINK_TOKENS, new OrderField[] { LinkTokens.LINK_TOKENS.UUID }, true);
        public static Index PLAYERS_PRIMARY = Internal.createIndex("PRIMARY", Players.PLAYERS, new OrderField[] { Players.PLAYERS.UUID }, true);
    }
}
