/*
 * This file is generated by jOOQ.
 */
package me.aa07.parautil.database;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import me.aa07.parautil.database.tables.LinkTokens;
import me.aa07.parautil.database.tables.LinkedAccounts;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ParadiseMc extends SchemaImpl {

    private static final long serialVersionUID = -293540959;

    /**
     * The reference instance of <code>paradise_mc</code>
     */
    public static final ParadiseMc PARADISE_MC = new ParadiseMc();

    /**
     * The table <code>paradise_mc.linked_accounts</code>.
     */
    public final LinkedAccounts LINKED_ACCOUNTS = me.aa07.parautil.database.tables.LinkedAccounts.LINKED_ACCOUNTS;

    /**
     * The table <code>paradise_mc.link_tokens</code>.
     */
    public final LinkTokens LINK_TOKENS = me.aa07.parautil.database.tables.LinkTokens.LINK_TOKENS;

    /**
     * No further instances allowed
     */
    private ParadiseMc() {
        super("paradise_mc", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            LinkedAccounts.LINKED_ACCOUNTS,
            LinkTokens.LINK_TOKENS);
    }
}
