/*
 * This file is generated by jOOQ.
 */
package me.aa07.parautil.database;


import javax.annotation.Generated;

import me.aa07.parautil.database.tables.LinkTokens;
import me.aa07.parautil.database.tables.LinkedAccounts;


/**
 * Convenience access to all tables in paradise_mc
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>paradise_mc.linked_accounts</code>.
     */
    public static final LinkedAccounts LINKED_ACCOUNTS = me.aa07.parautil.database.tables.LinkedAccounts.LINKED_ACCOUNTS;

    /**
     * The table <code>paradise_mc.link_tokens</code>.
     */
    public static final LinkTokens LINK_TOKENS = me.aa07.parautil.database.tables.LinkTokens.LINK_TOKENS;
}
