name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    name: Compile ParaUtil
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout files
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install Dependencies
        env:
          MVN_USER: ${{ secrets.mvnuser }}
          MVN_PASS: ${{ secrets.mvnpass }}
        run: mvn -Drepo.id=aa07_parautil_read -Drepo.login=$MVN_USER -Drepo.pwd=$MVN_PASS dependency:resolve

      - name: Build with Maven
        run: mvn package
